### ISSUE TITLE
Không lưu secret key trên repository

### ISSUE THREAD

**Issue by maytinhdibo** [nguyepham/Postcrunch_backend#1]
`src/main/java/nguye/postcrunch/backend/security/Constants.java`

**Comment by nguyepham** [comment]
Nếu không lưu trên repo mà người khác muốn clone về chạy thì lại phải gửi riêng ạ?

**Comment by maytinhdibo** [comment]
> Nếu không lưu trên repo mà người khác muốn clone về chạy thì lại phải gửi riêng ạ?

Đúng rồi, cái này là quy tắc bảo mật cơ bản.

**Comment by nguyepham** [comment]
> Đúng rồi, cái này là quy tắc bảo mật cơ bản.
>
 Vâng
